# Generated by Django 4.1 on 2022-09-21 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0030_alter_boardinghouse_phone_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardinghouse',
            name='latitude',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='boardinghouse',
            name='longitude',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Longitude'),
        ),
    ]
