# Generated by Django 4.1 on 2022-09-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0031_boardinghouse_latitude_boardinghouse_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardinghouse',
            name='latitude',
            field=models.IntegerField(blank=True, max_length=50, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='boardinghouse',
            name='longitude',
            field=models.IntegerField(blank=True, max_length=50, null=True, verbose_name='Longitude'),
        ),
    ]
