# Generated by Django 4.1 on 2022-09-27 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0033_alter_boardinghouse_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardinghouse',
            name='detail',
        ),
    ]
