# Generated by Django 4.1 on 2022-09-28 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0036_alter_boardinghouse_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardinghouse',
            name='admin_approve',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
