# Generated by Django 4.1 on 2022-09-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0038_alter_boardinghouse_admin_approve'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardinghouse',
            name='admin_approve',
        ),
        migrations.AddField(
            model_name='boardinghouse',
            name='admin_approval',
            field=models.CharField(choices=[('APPROVED', 'APPROVED'), ('DENIED', 'DENIED')], default=1, max_length=200),
            preserve_default=False,
        ),
    ]
