# Generated by Django 4.1 on 2022-09-28 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0042_alter_boardinghouse_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardinghouse',
            old_name='picture',
            new_name='picture1',
        ),
        migrations.AddField(
            model_name='boardinghouse',
            name='picture2',
            field=models.FileField(default=1, upload_to='bh-images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boardinghouse',
            name='picture3',
            field=models.FileField(default=1, upload_to='bh-images/'),
            preserve_default=False,
        ),
    ]
