# Generated by Django 4.1 on 2022-09-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0046_alter_boardinghouse_picture1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardinghouse',
            name='picture1',
            field=models.FileField(blank=True, null=True, upload_to='bh-images/'),
        ),
        migrations.AlterField(
            model_name='boardinghouse',
            name='picture2',
            field=models.FileField(blank=True, null=True, upload_to='bh-images/'),
        ),
        migrations.AlterField(
            model_name='boardinghouse',
            name='picture3',
            field=models.FileField(blank=True, null=True, upload_to='bh-images/'),
        ),
    ]
